from tkinter import *
import tkinter.messagebox as tmsg
def myfunc():
    print("hello How cn I help You")
    tmsg.showerror("Help","I will help you with this GUI")
root=Tk()
root.geometry("577x577")
root.title(" GUI program using Tkinter")
mainmenu=Menu(root)
m1=Menu(mainmenu,tearoff=0)
m1.add_command(label="newproject",command=myfunc)
m1.add_command(label="Save as",command=myfunc)
m1.add_separator()
m1.add_command(label="Save",command=myfunc)
m1.add_command(label="Print",command=myfunc)
m1.add_checkbutton(label="yes I want to quit",command=quit)
root.config(menu=mainmenu)
mainmenu.add_cascade(label="File",menu=m1)

m2=Menu(mainmenu,tearoff=0)
m2.add_command(label="Copy",command=myfunc)
m2.add_command(label="Paste",command=myfunc)
m2.add_separator()
m2.add_command(label="Cut",command=myfunc)
m2.add_command(label="share",command=myfunc)
m2.add_checkbutton(label="yes I want to quit",command=quit)
root.config(menu=mainmenu)
mainmenu.add_cascade(label="Edit",menu=m2)

m3=Menu(mainmenu,tearoff=0)
m3.add_command(label="Autosave",command=myfunc)
m3.add_command(label="Undo",command=myfunc)
m3.add_separator()
m3.add_command(label="Redo",command=myfunc)
m3.add_command(label="Find",command=myfunc)
m3.add_checkbutton(label="yes I want to quit",command=quit)
root.config(menu=mainmenu)
mainmenu.add_cascade(label="Selection",menu=m3)

m4=Menu(mainmenu,tearoff=0)
m4.add_command(label="Replace",command=myfunc)
m4.add_command(label="Select all",command=myfunc)
m4.add_separator()
m4.add_command(label="add configuration",command=myfunc)
m4.add_command(label="Run",command=myfunc)
m4.add_checkbutton(label="yes I want to quit",command=quit)
root.config(menu=mainmenu)
mainmenu.add_cascade(label="View",menu=m4)

root.mainloop()